<a href="https://colab.research.google.com/github/pascal-bergeron/ai4forgood2016/blob/main/FeatureBuilding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from google.colab import drive

In [2]:
drive.mount('/content/drive/')

Mounted at /content/drive/


In [3]:
cp 'drive/My Drive/Projects/AIForGood2020/' . -r

In [15]:
cp '../drive/My Drive/Projects/AIForGood2020/organisation.xlsx' .

In [5]:
cd AIForGood2020/

/content/AIForGood2020


In [6]:
# !unrar e -p*hack20 211GrandMontreal_DataPack.rar

# Agencies Taxonomomies

In [16]:
org = pd.read_excel('organisation.xlsx')

In [17]:
org.set_index('ResourceAgencyNum', inplace=True)

In [18]:
org.tail()

PublicName  ...                                      TaxonomyCodes
ResourceAgencyNum                                                     ...                                                   
30790854                BIBLIOTHÈQUE PUBLIQUE DE DOLLARD-DES-ORMEAUX  ...  TJ-4400; TJ-1800.6650; TJ-4500.2900; TJ-4500.1...
51229060                      BIBLIOTHÈQUE MUNICIPALE DE NAPIERVILLE  ...  TJ-4400; TJ-1800.6650; TJ-4500.1500-800; TJ-45...
49492168           BIBLIOTHÈQUE MUNICIPALE DE SAINT-JACQUES-LE-MI...  ...                              TJ-4400; TJ-1800.6650
18766848               BOISBRIAND - LOISIRS, CULTURE ET BIBLIOTHÈQUE  ...                        TD-0300.1200 * PL-7000.4360
42388216                                                 REBOND (LE)  ...   PS-9800.9800; TJ-1800.3300-600.10 * YB-9500.0500

[5 rows x 19 columns]

In [34]:
def get_level_2_taxonomy_code_list(ser: pd.Series) -> pd.Series:
  first_split = ser.str.split("; ")
  return first_split.apply(lambda x : np.nan if isinstance(x, float) and np.isnan(x) else [y[:7] for y in x] )

In [37]:
org['L2_tax_codes'] = get_level_2_taxonomy_code_list(org['TaxonomyCodes'])

In [39]:
org['L2_tax_codes'].head()

ResourceAgencyNum
34515394                                   [TD-6500, TD-1600]
18764735    [TC-5500, YH-6000, ND-3500, HH-0500, HH-0500, ...
18762709                                   [TN-4600, FT-4800]
18765353    [BM-8500, BD-1800, TI-1800, TI-1800, TI-1800, ...
54247598    [TD-1600, PS-8000, RP-1400, PH-0320, RP-1400, ...
Name: L2_tax_codes, dtype: object

# Needs 

In [40]:
besoins = pd.read_excel('Besoins.xlsx')

In [41]:
besoins.set_index('ReportNeedNum', inplace=True)

In [42]:
besoins.tail()

CallReportNum  ... TaxonomyName_link
ReportNeedNum                 ...                  
21475026            78145762  ...               NaN
21475411            78146045  ...               NaN
21475365            78146045  ...               NaN
21475383            78146045  ...               NaN
21475338            78146045  ...               NaN

[5 rows x 20 columns]

In [43]:
len(besoins.TaxonomyCode_full.unique())

1800

In [44]:
len(besoins.Level1Code.unique())

11

In [45]:
len(besoins.Level2Code.unique())

73

In [46]:
len(besoins.Level3Code.unique())

375

# References

In [48]:
references = pd.read_excel('Références.xlsx')

In [49]:
references.tail()

CallReportNum  ...  ReportNeedNum
264317       78146045  ...       21475383
264318       78146045  ...       21475383
264319       78146045  ...       21475338
264320       78146045  ...       21475383
264321       78146045  ...       21475411

[5 rows x 4 columns]

In [50]:
resource_ref_count= references.groupby('ResourceAgencyNum')['CallReportNum'].count().sort_values(ascending=False)

In [58]:
resource_agency_nums = resource_ref_count[resource_ref_count > 10].index.astype(int).dropna().values
np.sort(resource_agency_nums)

array([18759962, 18759964, 18759965, ..., 68848329, 68933670, 69147049])

In [60]:
resource_agency_nums

array([18760559, 47945224, 18761956, ..., 18762324, 34051134, 18762122])

In [61]:
len(references)

264322

In [62]:
ref = references.dropna()

In [63]:
ref['ResourceAgencyNum_int'] = ref['ResourceAgencyNum'].astype(int)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [66]:
ref

CallReportNum  ResourceAgencyNum  ... ReportNeedNum  ResourceAgencyNum_int
0            51805319         18762230.0  ...      12443066               18762230
1            51805954         18760351.0  ...      12443170               18760351
2            51805954         18762550.0  ...      12443170               18762550
3            51806285         18762497.0  ...      12443222               18762497
4            51806377         18763063.0  ...      12443241               18763063
...               ...                ...  ...           ...                    ...
264317       78146045         18762631.0  ...      21475383               18762631
264318       78146045         18760262.0  ...      21475383               18760262
264319       78146045         18762552.0  ...      21475338               18762552
264320       78146045         18762552.0  ...      21475383               18762552
264321       78146045         41529174.0  ...      21475411               41529174

[260257 rows x 5 columns]

In [70]:
tmp = ref[['CallReportNum','ResourceAgencyNum_int']].groupby('CallReportNum')['ResourceAgencyNum_int'].apply(list).values

In [53]:
from sklearn.preprocessing import MultiLabelBinarizer

In [72]:
Y = MultiLabelBinarizer().fit_transform(tmp)

In [73]:
Y

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])